### ISSUE TITLE
Name conflict with already existing project?

### ISSUE THREAD

**Issue by stephan75** [westnordost/osmapi#1]
Hello Westnordost,

are you aware that there is already a project listet in the OSM wiki at

http://wiki.openstreetmap.org/wiki/Osmapi ?

It seems to be a different and older project then yours, or am I wrong?

When renaming is a better way, maybe you can add a "J" letter in your project name? ;-)

**Comment by westnordost** [comment]
Hi Stephan

Yes, I am aware of it. The wiki article is about a _Python_ library that gets map data via the Osm Api 0.6, this project is a _Java_ library. 

Since it is for two different languages, I do not see that much of a conflict there. If someone wants to write a wiki article in the OSM wiki, then the article could be http://wiki.openstreetmap.org/wiki/Osmapi_(Java) or something. The problem with _"**j**osmapi"_ is that the name "JOSM" is already associated in the minds of everyone who does anything with OSM with the popular editor. So the first thing I think of when reading that is that it must have something to do with JOSM. 
With a Java project called "osmapi" it is immediately clear from the name what it is for, in my opinion.

**Comment by stephan75** [comment]
ok ... so we don't need looking for naming alternatives like osmjapi or similar ... 

then I will close this issue.
