### ISSUE TITLE
Add Simple HTTP Auth option for OsmConnection

### ISSUE THREAD

**Issue by snorkel123** [westnordost/osmapi#14]

**Comment by westnordost** [comment]
Won't implement

**Comment by snorkel123** [comment]
Could you elaborate on this?
I just need to make calls on user behalf w/o hassle with keys.

**Comment by westnordost** [comment]
As rude as it may sound, it is simply a deliberate decision I took to not implement simple HTTP auth, because there is a better alternative. The reason being that in my opinion, simple auth through third parties (=not from within openstreetmap.org) is considered very much deprecated and I don't want to promote it.
If you need write access to the OSM API, you are developing some kind of editor or bot, in which case using OAuth should be strongly encouraged as well. The informed user would not like to enter his OSM-credentials into some third-party app.

But as it is open source, you always have the option to modify it to your liking and use the modified version.
