### ISSUE TITLE
Upload GPX file

### ISSUE THREAD

**Issue by jamescr** [westnordost/osmapi#36]
I would like to use this awesome library in OSMTracker App (I'm in the process of giving love to the App). For this purpose, I'll require a method to upload a trace given a GPX File. 

I [played a little with the library code to explore how to implement this method](https://github.com/westnordost/osmapi/commit/96b295f6339d9a1755b328c8516d515a30daed3e). My implementation proposal is:
 (a) add a new `APIRequestWriter` implementation, `GpxFileWriter` that writes the content of the Gpx File to be uploaded  
 (b) add a new `create` method in `GpsTracesApi` with a File as param, instead of the Points. 
 
I could provide a PR (once I fixed some issues with Gradle in my repo), but I already have the code running, including a JUnit test.

**Comment by westnordost** [comment]
Hmm, indeed, a curious omission from the API. Uploading traces is the only point in the API though where uploading files should be the standard case.

I think your proposal is on point, that's exactly how I think an implementation should be done. Would you care open a PR?

Instead of a `File`, I think it would be more flexible to accept any `InputStream` as a parameter, i.e. make that writer a `GpxInputStreamWriter`.

**Comment by jamescr** [comment]
Great!.  Agree on the `GpxInputStreamWriter`.  Sure, I'll open the PR. Thanks.

**Comment by westnordost** [comment]
fixed by #37
