### ISSUE TITLE
Cannot Resolve the Constructor OSMConnection

### ISSUE THREAD

**Issue by ghost** [westnordost/osmapi#6]
Hi I am trying to implement 
OsmConnection osm = new OsmConnection(
                              "https://api.openstreetmap.org/api/0.6/",
                              "myappname");

but there is problem as Cannot Resolve the Constructor OSMConnection

**Comment by westnordost** [comment]
Hey rahullab
The constructor has 3 parameters: API URL, user agent, OAuthConsumer. If you do not use any API calls that require authentication, OAuthConsumer can be null. 

But you are right, I mention a non-existing constructor in the README.md, will correct that.

**Comment by westnordost** [comment]
Did that now

**Comment by ghost** [comment]
Hey thanks.. Its working :+1:  By the way are there any examples(App) using this library ?

**Comment by westnordost** [comment]
Well, I am using it myself in https://github.com/westnordost/osmagent

I don't think however that reading through this source code would make it clearer how to use osmapi since there is so much other code in this project.
I was hoping that the usage is self-explanatory from the README.md and the javadocs. If it isn't, you can open up another issue here and I will make the documentation clearer for that point.
